config/routes.rb
Footclan::Application.routes.draw do

 get "shoes/index"
  root 'users#main'
  get "/register", to: 'users#new'
  get "/login", to: 'sessions#new'
  get "/dashboard", to: 'users#index'
  get "/add_user", to: 'users#add_user'
  get "/search", to: 'shoes#search'

  resources :users
  resources :sessions
  resources :shoes do
    resources :comments
  end
  

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :shoe
  belongs_to :user
  
  validates :comment, presence: true, length: { minimum: 2 }
end

app/models/shoe.rb
class Shoe < ActiveRecord::Base

  belongs_to :user
  has_many :comments, dependent: :destroy


  validates :name, presence: true
  validates :image, presence: true
  
  mount_uploader :image, ImageUploader
  
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :comments
	has_many :shoes
	
	EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
	validates :first_name, :last_name, presence: true, length: { in: 2..20 }
	validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }


	before_save do
		self.email.downcase!
		if User.any?
			self.user_level = 1
		else
			self.user_level = 9
		end
	end
	
	has_secure_password

	def admin?
		self.user_level == 9
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    include SessionsHelper
    include UsersHelper

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :signed_in_user, only:[:create]

	def create
		if Shoe.find(params[:shoe_id]).comments += [current_user.comments.new(comment_params)]
			redirect_to shoe_path(params[:shoe_id])
		else
			redirect_to shoe_path(params[:shoe_id]), flash: { message: "Comment must be two characters" }
		end
	end

	private

	def comment_params
		params.require(:comment).permit(:comment)
	end

	def signed_in_user
		redirect_to root_path, notice: "Please sign in" unless signed_in?
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 
  def create
  	user = User.find_by(email: params[:user][:email]).try(:authenticate, params[:user][:password])
  	if user == false || user.nil?
  		redirect_to login_path, flash: { message: "Incorrect email/password" }
  	else
  		sign_in(user)
  		redirect_to root_path(user)
  	end
  end

  def new
  	@user = User.new
  end

  def destroy
  	sign_out
  	redirect_to root_path
  end
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController

	  before_action :signed_in_user, only: [:create]

	def new
		@shoe = Shoe.new
	  	@shoes = Shoe.all
	end

	def create
		if current_user.shoes += [Shoe.new(shoe_params)]
			redirect_to new_shoe_path
		else
			redirect_to shoes, flash: { message: "Upload issue" }
		end
	end

	def show
		@shoe = Shoe.find(params[:id])
		@comment = Comment.new
		@comments = @shoe.comments.order("created_at DESC")
	end

	def destroy
		@shoe = Shoe.find(params[:id])
		@shoe.destroy
		respond_to do |format|
      format.html { redirect_to new_shoe_path }
      format.json { head :no_content }
		end
	end

	def search
		@shoes = Shoe.where("name like ?", "%#{params[:search]}%")
	end

	private

	def shoe_params
		params.require(:shoe).permit(:name, :image)
	end

	def signed_in_user
		redirect_to root_path, notice: "Please sign in" unless signed_in?
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def main
    @shoe = Shoe.new
    @shoes = Shoe.all
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      if signed_in? and current_user.admin?
        redirect_to dashboard_path, flash: { success: "User created" }
      else
  		  redirect_to login_path, flash: { message: "Registration succesfull, please log in" }
      end
  	else
  		redirect_to register_path, flash: { errors: @user.errors.full_messages }
  	end
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
  	@user = User.find(params[:id])
  end

  def add_user
  	@user = User.new
  end

  def destroy
  	@user = User.find(params[:id])
    if current_user?(@user)
      flash[:error] = "Can't delete self"
    else
      @user.destroy
      flash[:success] = "User deleted."
    end
    redirect_to dashboard_path
  end

  private

  def user_params
  	params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def admin_user
  	redirect_to root_path unless current_user.admin?
  end

  def signed_in_user
    redirect_to login_path, notice: "Please sign in." unless signed_in? 
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless (current_user?(@user) or current_user.admin?)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in user
		session[:user_id] = user.id
	end

	def current_user= user
		@current_user = user
	end

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		session[:user_id] = nil
		self.current_user = nil
	end

	def current_user? user
		user === current_user
	end

	def deny_access
		redirect_to new_user_path, notice: "Please sign in to access this page."
	end
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def admin?
		@current_user.user_level == 9
	end
end

app/views/layouts/_error_printer.html.erb
<% if flash[:errors] %>
	<% flash[:errors].each do |error| %>
		<p><%= error %></p>
	<% end %>
<% end %>
<% if flash[:message] %>
	<p><%= flash[:message] %></p>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
	
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
        <li><h2 class="pull-left"><%= link_to "Foot-clan.co", root_path %></h2></li>
        <li><%= link_to "Upload", new_shoe_path %></li>
        <% if signed_in? %>
      	  <li class="pull-right"><%= form_tag(search_path, method: "get")  do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search" %>
        <%= submit_tag "Search" %>
        <% end %></li>
        <% end %>
        <li class="pull-right"><a href="mailto:footclanco@gmail.com"> Contact Us</a></li>

        <% if signed_in? %>
    		<li class="pull-right"><%= link_to 'Log out', session_path(current_user), method: "delete" %></li>
    	<% else %>
    		<li class="pull-right"><%= link_to "Register", register_path %></li>
    		<li class="pull-right"><%= link_to "Log in", login_path %></li>
    	<% end %>
      

    </ul>
    <ul class="nav navbar-nav navbar-right">
      
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container"  >
<%= render "layouts/header" %>
<%= yield %>
</body>


</html>
</div>

app/views/shoes/new.html.erb
<div class="row">
<div class="upload-not-logged col-md-6" >
 <p class="lead center center"></p>
  <div class="row">
    <div class='col-md-9 home-div'>
      <div class="home-info lead well use" style="background-image: -webkit-linear-gradient(top, rgb(255, 255, 255), rgb(195, 218, 247)); background-color: rgb(195, 218, 247);">
        <h3 class="lead aboutbox">Register to Upload!</h3>
        <div>
          <p class="hometext">1. Shoe name , size , price, condition.</p>
          <p class="hometext">2. Comment shoe with your email for purchase interest.</p>
          <p class="hometext">3. Wait for response and negotiate price</p>
        </div>
      </div>
    </div>
</div>
</div>




<% if signed_in? %>


<div class="row">
<div class="col-md-3">
	<h4>Welcome <%= current_user.first_name %> </h4>

	<h3>Upload a Photo</h3>
	<% if flash[:message] %>
		<p><%= flash[:message] %></p>
	<% end %>
	<!-- Make sure multipart: true is in your form to allow file upload -->
<%= simple_form_for(@shoe, :defaults => { :wrapper_html => {:class=>"form-group"}, :input_html => { :class => "form-control" } }) do |f| %>		
		<%= f.input :name, label: "Name:", class: "col-md-3"%>
		<!-- file_field for file upload -->
		<%= f.file_field :image %>
		<%= f.button :submit, value: "Upload", class: "btn btn-primary" %>
	<% end %>

</div>
</div>

<div class="row">
<div class="col-md-12">
<h3>Gallery</h3>
<% @shoes.each do |shoe| %>
	<div class="col-md-3">
		<h6><%= shoe.name %></h6>
		<a href="<%= shoe_path(shoe) %>">
			<!-- photo.image_url gets the url using the carrierwave gem -->
			<%= image_tag shoe.image_url.to_s, width: 200 %>
		</a>
	</div>
	<% end %>

<% end %>
</div>
</div>

app/views/shoes/search.html.erb
<h3>Resutls</h3>
<% @shoes.each do |shoe| %>
	<div class="col-md-3">
		<h6><%= shoe.name %></h6>
		<a href="<%= shoe_path(shoe) %>">
			<!-- photo.image_url gets the url using the carrierwave gem -->
			<%= image_tag shoe.image_url.to_s, width: 200 %>
		</a>
	</div>
<% end %>

app/views/shoes/show.html.erb
<h1><%= @shoe.name %></h1>
<%= image_tag @shoe.image_url.to_s %>
<h3>Comment</h3>
<% if flash[:message] %>
	<p><%= flash[:message] %></p>
<% end %>
<% if signed_in? %>
	<%= simple_form_for [@shoe, @comment] do |f| %>
		<%= f.text_area :comment %><br>
		<%= f.button :submit, value: "Leave Comment", class: "btn btn-primary" %>
	<% end %>
<% end %>
<% @comments.each do |comment| %>
	<h5><%= comment.user.first_name %></h5>
	<p><%= comment.comment %></p>
<% end %>

<%= link_to "destroy image", @shoe ,method: :delete, image: {confirm: 'Are you sure?'}if admin? %>

app/views/users/_new_user.html.erb
<%= render "layouts/error_printer" %>
<div class="col-md-6">
<%= simple_form_for(@user, :defaults => { :wrapper_html => {:class=>"form-group"}, :input_html => { :class => "form-control" } }) do |f| %>	


<%= f.input :first_name, label: "First name" %>
	<%= f.input :last_name, label: "Last name" %>
	<%= f.input :email, label: "Email"%>
	<%= f.input :password, label: "Password" %>
	<%= f.input :password_confirmation, label: "Confirm Password" %>
	<%= f.button :submit, value: "Register", class: 'btn btn-primary' %>
<% end %>
</div>

app/views/users/main.html.erb
      <div class="container" >
  <div class="title center">
<h2 class="foot">Join Foot-Clan the resource to post and sell shoes</h2>  
</div>


  <div class="register ">
       <div class='col-md-6 home-div'>
      <div class="home-info lead well use" style="background-image: -webkit-linear-gradient(top, rgb(255, 255, 255), rgb(195, 218, 247)); background-color: rgb(195, 218, 247);">
            <p class="hometext">Register</p>
            <p class="hometext">Maybe you want to sell shoes.</p>
            <p class="hometext">Maybe you're tired of paying fees to ebay.</p>
            <p class="hometext">Join Foot-Clan now for FREE to stop giving away your profits to fees</p>
          </div>
      </div>
    </div>

<div class="sell">
    <div class='col-md-6 home-div'>
      <div class="home-info lead well use" style="background-image: -webkit-linear-gradient(top, rgb(255, 255, 255), rgb(195, 218, 247)); background-color: rgb(195, 218, 247);">
            <p class="hometext">Sell</p>
        <p class="hometext">Foot-clan allows users to upload photos of shoes they want to sell. </p>
        <p> Gives you an opportunity to skip ebay fees and free you from scouring craigslist, ebay, and facebook to find the sneaker you need!</p>
      </div>
    </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Register") %>
<h1>Register</h1>

<%= render "new_user" %>